class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start4'
        self.MirrorCommand = 'mirror4'
        self.UnzipMirrorCommand = 'unzipmirror4'
        self.TarMirrorCommand = 'tarmirror4'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall1'
        self.ListCommand = 'list141'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'authorize4'
        self.UnAuthorizeCommand = 'unauthorize4'
        self.PingCommand = 'ping4'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help45546456'
        self.LogCommand = 'log4'
        self.SpeedCommand = 'speedtest4'
        self.CloneCommand = 'clone4'
        self.WatchCommand = 'watch4'
        self.TarWatchCommand = 'tarw4'
        self.DeleteCommand = 'd'
        self.UsageCommand = 'usage4'
        self.RepoCommand = 'repo0025'

BotCommands = _BotCommands()
